[[redirects]]
from = "/apps/frontend/blog/*"
to = "/apps/frontend/blog/index.html"
status = 200
force = true

[[redirects]]
from = "/apps/frontend/easy-tools/*"
to = "/apps/frontend/easy-tools/index.html"
status = 200                # 保持 HTTP 200 状态码（非重定向）
force = true                # 强制覆盖所有匹配规则